// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function flatMapError(result, fn) {
  if (result.TAG === /* Ok */0) {
    return {
            TAG: /* Ok */0,
            _0: result._0
          };
  } else {
    return Curry._1(fn, result._0);
  }
}

function mapError(fn, __x) {
  return flatMapError(__x, (function (value) {
                return {
                        TAG: /* Error */1,
                        _0: Curry._1(fn, value)
                      };
              }));
}

var t = {
  TAG: /* Ok */0,
  _0: "12"
};

exports.flatMapError = flatMapError;
exports.mapError = mapError;
exports.t = t;
/* No side effect */
