// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");

function map(taskResult, fn, param) {
  return Curry._1(taskResult, undefined).then(function (__x) {
              return Belt_Result.map(__x, fn);
            });
}

function flatMap(taskResult, fn, param) {
  return Curry._1(taskResult, undefined).then(function (result) {
              if (result.TAG === /* Ok */0) {
                return Curry._2(fn, result._0, undefined);
              } else {
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: result._0
                          });
              }
            });
}

function make(value, param) {
  return Promise.resolve({
              TAG: /* Ok */0,
              _0: value
            });
}

function flatMapFirst(fn, __x) {
  return function (param) {
    return flatMap(__x, (function (value) {
                  var value$1 = Curry._1(fn, value);
                  var partial_arg;
                  partial_arg = value$1.TAG === /* Ok */0 ? ({
                        TAG: /* Ok */0,
                        _0: value
                      }) : ({
                        TAG: /* Error */1,
                        _0: value$1._0
                      });
                  return function (param) {
                    return Promise.resolve({
                                TAG: /* Ok */0,
                                _0: partial_arg
                              });
                  };
                }), param);
  };
}

function t(param) {
  return map((function (param) {
                return new Promise((function (resolve, param) {
                              return resolve({
                                          TAG: /* Ok */0,
                                          _0: 200
                                        });
                            }));
              }), (function (param) {
                return "12";
              }), param);
}

exports.map = map;
exports.flatMap = flatMap;
exports.make = make;
exports.flatMapFirst = flatMapFirst;
exports.t = t;
/* No side effect */
